stages:
- name: build
  steps:
  - runScriptConfig:
      image: wangzhenalex/maven-aliyun
      shellScript: |-
        cd /opt/data
        mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: binguanghui/k8s-example
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./k8s-example.yaml
timeout: 60
notification: {}
