apiVersion: v1
kind: Pod
metadata:
  name: testcm1-pod
spec:
  containers:
    - name: testcm1
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: JACK
          valueFrom:
            configMapKeyRef:
              name: from-code-cm
              key: jack
        - name: TOM
          valueFrom:
            configMapKeyRef:
              name: from-code-cm
              key: tom